osx_image: xcode12u
os: osx
language: python

cache:
    directories:
        - node_modules
        - $HOME/.electron
        - $HOME/.cache
addons:
    apt:
        packages:
            - libgnome-keyring-dev
            - icnsutils
install:
    - 'nvm install 10'
    - 'curl -o- -L https://yarnpkg.com/install.sh | bash'
    - 'source ~/.bashrc'
    - 'npm install -g xvfb-maybe'
    - yarn
script:
    - 'yarn run dist'

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  draft: true
  file:
    - "dist/mac-arm64/*"