version: "{build}"

image:
  - Visual Studio 2019
  - macos

platform:
  - x64

for:
-
  #------------------
  # Windows 10
  #------------------
  matrix:
    only:
      - image: Visual Studio 2019
  init:
    - git config --global core.autocrlf input
  install:
    - 'ps: Install-Product node 10 x64'
    - 'git reset --hard HEAD'
    - 'yarn'
    - 'node --version'
  cache:
    - node_modules
    - '%APPDATA%\npm-cache'
    - '%USERPROFILE%\.electron'
    - '%USERPROFILE%\AppData\Local\Yarn\cache'
  build_script:
    - 'yarn run dist'
-
  #------------------
  # MacOS
  #------------------
  matrix:
    only:
      - image: macos
  # scripts that are called at very beginning, before repo cloning
  init:
    - system_profiler SPSoftwareDataType
    - cmake --version
    - gcc -v
  # scripts that run after cloning repository
  install:
    - 'nvm install 10'
    - 'curl -o- -L https://yarnpkg.com/install.sh | bash'
    - 'source ~/.bashrc'
    - 'npm install -g xvfb-maybe'
    - 'yarn'
  cache:
    - node_modules
    - $HOME/.electron
    - $HOME/.cache
  build_script:
    - 'yarn run dist'