version: 0.1.{build}

image:
  - macOS
platform:
  - x64

cache:
  #- node_modules
  #- '%APPDATA%\npm-cache'
  #- '%USERPROFILE%\.electron'
  #- '%USERPROFILE%\AppData\Local\Yarn\cache'
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

init:
  - git config --global core.autocrlf input

install:
  - 'nvm install 10'
  - 'curl -o- -L https://yarnpkg.com/install.sh | bash'
  - 'source ~/.bashrc'
  - 'npm install -g xvfb-maybe'
  - yarn
  #- ps: Install-Product node 10 x64
  #- git reset --hard HEAD
  #- yarn
  #- node --version

build_script:
  - yarn run dist

test: off
